export const DEFAULT_LEFT_SIDEBAR_VISIBILITY = true
export const DEFAULT_RIGHT_SIDEBAR_VISIBILITY = true

export const DEFAULT_MINIMAP_VISIBILITY = true

export const DEFAULT_ANNOTATIONS_VISIBILITY = true
export const DEFAULT_ANNOTATION_CLASS_VISIBILITY = true
