name: Build / Release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔩 Install Dependencies
        run: yarn

      - name: 🏗️ build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: 🏗️ build-mac
        if: matrix.os == 'macos-latest'
        run: yarn build:mac

      - name: 🏗️ build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
